name: Output information
on: [workflow_dispatch]
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub context
        run: echo "${{ toJSON(github) }}"
      - name: Output information
        run: |
          echo "Author: ${{ github.actor }}"
          echo "Branch: ${{ github.ref }}"
